package com.ddz.domain.entity;

import java.io.Serializable;

public class AccountRoleEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_role.F_ACCOUNT_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long accountRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_role.F_ACCOUNT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_role.F_ACCOUNT_ROLE_ID
     *
     * @return the value of t_account_role.F_ACCOUNT_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getAccountRoleId() {
        return accountRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_role.F_ACCOUNT_ROLE_ID
     *
     * @param accountRoleId the value for t_account_role.F_ACCOUNT_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setAccountRoleId(Long accountRoleId) {
        this.accountRoleId = accountRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_role.F_ACCOUNT_ID
     *
     * @return the value of t_account_role.F_ACCOUNT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_role.F_ACCOUNT_ID
     *
     * @param accountId the value for t_account_role.F_ACCOUNT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_role.F_ROLE_ID
     *
     * @return the value of t_account_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_role.F_ROLE_ID
     *
     * @param roleId the value for t_account_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", accountRoleId=").append(accountRoleId);
        sb.append(", accountId=").append(accountId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}