package com.ddz.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class AccountEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_ACCOUNT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_ACCOUNT_USERNAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String accountUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_ACCOUNT_PASSWORD
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String accountPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_NICKNAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_IS_DELETE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_IS_LOGIN
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Integer isLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_CREATOR
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_ACCOUNT_ID
     *
     * @return the value of t_account.F_ACCOUNT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_ACCOUNT_ID
     *
     * @param accountId the value for t_account.F_ACCOUNT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_ACCOUNT_USERNAME
     *
     * @return the value of t_account.F_ACCOUNT_USERNAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getAccountUsername() {
        return accountUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_ACCOUNT_USERNAME
     *
     * @param accountUsername the value for t_account.F_ACCOUNT_USERNAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setAccountUsername(String accountUsername) {
        this.accountUsername = accountUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_ACCOUNT_PASSWORD
     *
     * @return the value of t_account.F_ACCOUNT_PASSWORD
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_ACCOUNT_PASSWORD
     *
     * @param accountPassword the value for t_account.F_ACCOUNT_PASSWORD
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_NICKNAME
     *
     * @return the value of t_account.F_NICKNAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_NICKNAME
     *
     * @param nickname the value for t_account.F_NICKNAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_IS_DELETE
     *
     * @return the value of t_account.F_IS_DELETE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_IS_DELETE
     *
     * @param isDelete the value for t_account.F_IS_DELETE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_IS_LOGIN
     *
     * @return the value of t_account.F_IS_LOGIN
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Integer getIsLogin() {
        return isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_IS_LOGIN
     *
     * @param isLogin the value for t_account.F_IS_LOGIN
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setIsLogin(Integer isLogin) {
        this.isLogin = isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_CREATOR
     *
     * @return the value of t_account.F_CREATOR
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_CREATOR
     *
     * @param creator the value for t_account.F_CREATOR
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_INDATE
     *
     * @return the value of t_account.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_INDATE
     *
     * @param indate the value for t_account.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.F_UPDATE_TIME
     *
     * @return the value of t_account.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.F_UPDATE_TIME
     *
     * @param updateTime the value for t_account.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", accountId=").append(accountId);
        sb.append(", accountUsername=").append(accountUsername);
        sb.append(", accountPassword=").append(accountPassword);
        sb.append(", nickname=").append(nickname);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", isLogin=").append(isLogin);
        sb.append(", creator=").append(creator);
        sb.append(", indate=").append(indate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}