package com.ddz.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class ActivityShareEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_share.F_ACTIVITY_SHARE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long activityShareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_share.F_ACTIVITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_share.F_SHARED_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long sharedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_share.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_share.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Date indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_share.F_ACTIVITY_SHARE_ID
     *
     * @return the value of t_activity_share.F_ACTIVITY_SHARE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getActivityShareId() {
        return activityShareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_share.F_ACTIVITY_SHARE_ID
     *
     * @param activityShareId the value for t_activity_share.F_ACTIVITY_SHARE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setActivityShareId(Long activityShareId) {
        this.activityShareId = activityShareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_share.F_ACTIVITY_ID
     *
     * @return the value of t_activity_share.F_ACTIVITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_share.F_ACTIVITY_ID
     *
     * @param activityId the value for t_activity_share.F_ACTIVITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_share.F_SHARED_ID
     *
     * @return the value of t_activity_share.F_SHARED_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getSharedId() {
        return sharedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_share.F_SHARED_ID
     *
     * @param sharedId the value for t_activity_share.F_SHARED_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setSharedId(Long sharedId) {
        this.sharedId = sharedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_share.F_USER_ID
     *
     * @return the value of t_activity_share.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_share.F_USER_ID
     *
     * @param userId the value for t_activity_share.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_share.F_INDATE
     *
     * @return the value of t_activity_share.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_share.F_INDATE
     *
     * @param indate the value for t_activity_share.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activityShareId=").append(activityShareId);
        sb.append(", activityId=").append(activityId);
        sb.append(", sharedId=").append(sharedId);
        sb.append(", userId=").append(userId);
        sb.append(", indate=").append(indate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}