package com.ddz.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class ActivityEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_ACTIVITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_ACTIVITY_KEY
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String activityKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_ACTIVITY_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_DESCRIBE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_REMARK
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_IS_DELETE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_ACTIVITY_ID
     *
     * @return the value of t_activity.F_ACTIVITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_ACTIVITY_ID
     *
     * @param activityId the value for t_activity.F_ACTIVITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_ACTIVITY_KEY
     *
     * @return the value of t_activity.F_ACTIVITY_KEY
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getActivityKey() {
        return activityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_ACTIVITY_KEY
     *
     * @param activityKey the value for t_activity.F_ACTIVITY_KEY
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setActivityKey(String activityKey) {
        this.activityKey = activityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_ACTIVITY_NAME
     *
     * @return the value of t_activity.F_ACTIVITY_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_ACTIVITY_NAME
     *
     * @param activityName the value for t_activity.F_ACTIVITY_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_DESCRIBE
     *
     * @return the value of t_activity.F_DESCRIBE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_DESCRIBE
     *
     * @param describe the value for t_activity.F_DESCRIBE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_REMARK
     *
     * @return the value of t_activity.F_REMARK
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_REMARK
     *
     * @param remark the value for t_activity.F_REMARK
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_INDATE
     *
     * @return the value of t_activity.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_INDATE
     *
     * @param indate the value for t_activity.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_IS_DELETE
     *
     * @return the value of t_activity.F_IS_DELETE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_IS_DELETE
     *
     * @param isDelete the value for t_activity.F_IS_DELETE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.F_UPDATE_TIME
     *
     * @return the value of t_activity.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.F_UPDATE_TIME
     *
     * @param updateTime the value for t_activity.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activityId=").append(activityId);
        sb.append(", activityKey=").append(activityKey);
        sb.append(", activityName=").append(activityName);
        sb.append(", describe=").append(describe);
        sb.append(", remark=").append(remark);
        sb.append(", indate=").append(indate);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}