package com.ddz.domain.entity;

import java.io.Serializable;

public class MenuRoleEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.F_MENU_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long menuRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.F_MENU_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.F_MENU_ROLE_ID
     *
     * @return the value of t_menu_role.F_MENU_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getMenuRoleId() {
        return menuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.F_MENU_ROLE_ID
     *
     * @param menuRoleId the value for t_menu_role.F_MENU_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setMenuRoleId(Long menuRoleId) {
        this.menuRoleId = menuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.F_MENU_ID
     *
     * @return the value of t_menu_role.F_MENU_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.F_MENU_ID
     *
     * @param menuId the value for t_menu_role.F_MENU_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.F_ROLE_ID
     *
     * @return the value of t_menu_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.F_ROLE_ID
     *
     * @param roleId the value for t_menu_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuRoleId=").append(menuRoleId);
        sb.append(", menuId=").append(menuId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}