package com.ddz.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class MenuEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_MENU_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_PARENT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_MENU_NAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_URL
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_PERMS
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_TYPE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_ICON
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_ORDER_NUM
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_MENU_ID
     *
     * @return the value of t_menu.F_MENU_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_MENU_ID
     *
     * @param menuId the value for t_menu.F_MENU_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_PARENT_ID
     *
     * @return the value of t_menu.F_PARENT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_PARENT_ID
     *
     * @param parentId the value for t_menu.F_PARENT_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_MENU_NAME
     *
     * @return the value of t_menu.F_MENU_NAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_MENU_NAME
     *
     * @param menuName the value for t_menu.F_MENU_NAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_URL
     *
     * @return the value of t_menu.F_URL
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_URL
     *
     * @param url the value for t_menu.F_URL
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_PERMS
     *
     * @return the value of t_menu.F_PERMS
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_PERMS
     *
     * @param perms the value for t_menu.F_PERMS
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_TYPE
     *
     * @return the value of t_menu.F_TYPE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_TYPE
     *
     * @param type the value for t_menu.F_TYPE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_ICON
     *
     * @return the value of t_menu.F_ICON
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_ICON
     *
     * @param icon the value for t_menu.F_ICON
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_ORDER_NUM
     *
     * @return the value of t_menu.F_ORDER_NUM
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_ORDER_NUM
     *
     * @param orderNum the value for t_menu.F_ORDER_NUM
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_INDATE
     *
     * @return the value of t_menu.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_INDATE
     *
     * @param indate the value for t_menu.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.F_UPDATE_TIME
     *
     * @return the value of t_menu.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.F_UPDATE_TIME
     *
     * @param updateTime the value for t_menu.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", parentId=").append(parentId);
        sb.append(", menuName=").append(menuName);
        sb.append(", url=").append(url);
        sb.append(", perms=").append(perms);
        sb.append(", type=").append(type);
        sb.append(", icon=").append(icon);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", indate=").append(indate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}