package com.ddz.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class RoleEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.F_ROLE_NAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.F_REMARK
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.F_CREATOR
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.F_ROLE_ID
     *
     * @return the value of t_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.F_ROLE_ID
     *
     * @param roleId the value for t_role.F_ROLE_ID
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.F_ROLE_NAME
     *
     * @return the value of t_role.F_ROLE_NAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.F_ROLE_NAME
     *
     * @param roleName the value for t_role.F_ROLE_NAME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.F_REMARK
     *
     * @return the value of t_role.F_REMARK
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.F_REMARK
     *
     * @param remark the value for t_role.F_REMARK
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.F_CREATOR
     *
     * @return the value of t_role.F_CREATOR
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.F_CREATOR
     *
     * @param creator the value for t_role.F_CREATOR
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.F_INDATE
     *
     * @return the value of t_role.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.F_INDATE
     *
     * @param indate the value for t_role.F_INDATE
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.F_UPDATE_TIME
     *
     * @return the value of t_role.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.F_UPDATE_TIME
     *
     * @param updateTime the value for t_role.F_UPDATE_TIME
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", roleName=").append(roleName);
        sb.append(", remark=").append(remark);
        sb.append(", creator=").append(creator);
        sb.append(", indate=").append(indate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}