package com.ddz.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class UserVoiceEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_voice.F_USER_VOICE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long userVoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_voice.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_voice.F_VOICE_PATH
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String voicePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_voice.F_VOICE_MESSAGE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String voiceMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_voice.F_IS_DELETE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_voice.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_voice.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_voice.F_USER_VOICE_ID
     *
     * @return the value of t_user_voice.F_USER_VOICE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getUserVoiceId() {
        return userVoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_voice.F_USER_VOICE_ID
     *
     * @param userVoiceId the value for t_user_voice.F_USER_VOICE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUserVoiceId(Long userVoiceId) {
        this.userVoiceId = userVoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_voice.F_USER_ID
     *
     * @return the value of t_user_voice.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_voice.F_USER_ID
     *
     * @param userId the value for t_user_voice.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_voice.F_VOICE_PATH
     *
     * @return the value of t_user_voice.F_VOICE_PATH
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getVoicePath() {
        return voicePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_voice.F_VOICE_PATH
     *
     * @param voicePath the value for t_user_voice.F_VOICE_PATH
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setVoicePath(String voicePath) {
        this.voicePath = voicePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_voice.F_VOICE_MESSAGE
     *
     * @return the value of t_user_voice.F_VOICE_MESSAGE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getVoiceMessage() {
        return voiceMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_voice.F_VOICE_MESSAGE
     *
     * @param voiceMessage the value for t_user_voice.F_VOICE_MESSAGE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setVoiceMessage(String voiceMessage) {
        this.voiceMessage = voiceMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_voice.F_IS_DELETE
     *
     * @return the value of t_user_voice.F_IS_DELETE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_voice.F_IS_DELETE
     *
     * @param isDelete the value for t_user_voice.F_IS_DELETE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_voice.F_INDATE
     *
     * @return the value of t_user_voice.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_voice.F_INDATE
     *
     * @param indate the value for t_user_voice.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_voice.F_UPDATE_TIME
     *
     * @return the value of t_user_voice.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_voice.F_UPDATE_TIME
     *
     * @param updateTime the value for t_user_voice.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userVoiceId=").append(userVoiceId);
        sb.append(", userId=").append(userId);
        sb.append(", voicePath=").append(voicePath);
        sb.append(", voiceMessage=").append(voiceMessage);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", indate=").append(indate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}