package com.ddz.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class UserEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_USER_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_PASSWORD
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_NICK_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_WX_OPENID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_WX_UNIONID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String wxUnionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_USER_UUID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_AVATAR
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_SEX
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_PROVICE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Integer proviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_CITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_DISTRICT_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Integer districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_STREET_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Integer streetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_ADDRESS
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_TEL
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_STATUS
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_VOICE_TOTAL
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long voiceTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_VOICE_COUNT
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Long voiceCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_USER_ID
     *
     * @return the value of t_user.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_USER_ID
     *
     * @param userId the value for t_user.F_USER_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_USER_NAME
     *
     * @return the value of t_user.F_USER_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_USER_NAME
     *
     * @param userName the value for t_user.F_USER_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_PASSWORD
     *
     * @return the value of t_user.F_PASSWORD
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_PASSWORD
     *
     * @param password the value for t_user.F_PASSWORD
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_NICK_NAME
     *
     * @return the value of t_user.F_NICK_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_NICK_NAME
     *
     * @param nickName the value for t_user.F_NICK_NAME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_WX_OPENID
     *
     * @return the value of t_user.F_WX_OPENID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_WX_OPENID
     *
     * @param wxOpenid the value for t_user.F_WX_OPENID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_WX_UNIONID
     *
     * @return the value of t_user.F_WX_UNIONID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getWxUnionid() {
        return wxUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_WX_UNIONID
     *
     * @param wxUnionid the value for t_user.F_WX_UNIONID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setWxUnionid(String wxUnionid) {
        this.wxUnionid = wxUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_USER_UUID
     *
     * @return the value of t_user.F_USER_UUID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_USER_UUID
     *
     * @param userUuid the value for t_user.F_USER_UUID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_AVATAR
     *
     * @return the value of t_user.F_AVATAR
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_AVATAR
     *
     * @param avatar the value for t_user.F_AVATAR
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_SEX
     *
     * @return the value of t_user.F_SEX
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_SEX
     *
     * @param sex the value for t_user.F_SEX
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_PROVICE_ID
     *
     * @return the value of t_user.F_PROVICE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Integer getProviceId() {
        return proviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_PROVICE_ID
     *
     * @param proviceId the value for t_user.F_PROVICE_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setProviceId(Integer proviceId) {
        this.proviceId = proviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_CITY_ID
     *
     * @return the value of t_user.F_CITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_CITY_ID
     *
     * @param cityId the value for t_user.F_CITY_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_DISTRICT_ID
     *
     * @return the value of t_user.F_DISTRICT_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_DISTRICT_ID
     *
     * @param districtId the value for t_user.F_DISTRICT_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_STREET_ID
     *
     * @return the value of t_user.F_STREET_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Integer getStreetId() {
        return streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_STREET_ID
     *
     * @param streetId the value for t_user.F_STREET_ID
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setStreetId(Integer streetId) {
        this.streetId = streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_ADDRESS
     *
     * @return the value of t_user.F_ADDRESS
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_ADDRESS
     *
     * @param address the value for t_user.F_ADDRESS
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_TEL
     *
     * @return the value of t_user.F_TEL
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_TEL
     *
     * @param tel the value for t_user.F_TEL
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_STATUS
     *
     * @return the value of t_user.F_STATUS
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_STATUS
     *
     * @param status the value for t_user.F_STATUS
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_VOICE_TOTAL
     *
     * @return the value of t_user.F_VOICE_TOTAL
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getVoiceTotal() {
        return voiceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_VOICE_TOTAL
     *
     * @param voiceTotal the value for t_user.F_VOICE_TOTAL
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setVoiceTotal(Long voiceTotal) {
        this.voiceTotal = voiceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_VOICE_COUNT
     *
     * @return the value of t_user.F_VOICE_COUNT
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Long getVoiceCount() {
        return voiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_VOICE_COUNT
     *
     * @param voiceCount the value for t_user.F_VOICE_COUNT
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setVoiceCount(Long voiceCount) {
        this.voiceCount = voiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_INDATE
     *
     * @return the value of t_user.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_INDATE
     *
     * @param indate the value for t_user.F_INDATE
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.F_UPDATE_TIME
     *
     * @return the value of t_user.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.F_UPDATE_TIME
     *
     * @param updateTime the value for t_user.F_UPDATE_TIME
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", nickName=").append(nickName);
        sb.append(", wxOpenid=").append(wxOpenid);
        sb.append(", wxUnionid=").append(wxUnionid);
        sb.append(", userUuid=").append(userUuid);
        sb.append(", avatar=").append(avatar);
        sb.append(", sex=").append(sex);
        sb.append(", proviceId=").append(proviceId);
        sb.append(", cityId=").append(cityId);
        sb.append(", districtId=").append(districtId);
        sb.append(", streetId=").append(streetId);
        sb.append(", address=").append(address);
        sb.append(", tel=").append(tel);
        sb.append(", status=").append(status);
        sb.append(", voiceTotal=").append(voiceTotal);
        sb.append(", voiceCount=").append(voiceCount);
        sb.append(", indate=").append(indate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}