package com.ddz.domain.mapper;

import com.ddz.domain.entity.AccountEntity;
import com.ddz.domain.entity.AccountEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AccountEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    long countByExample(AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int deleteByExample(AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Delete({
        "delete from t_account",
        "where F_ACCOUNT_ID = #{accountId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Insert({
        "insert into t_account (F_ACCOUNT_USERNAME, F_ACCOUNT_PASSWORD, ",
        "F_NICKNAME, F_IS_DELETE, ",
        "F_IS_LOGIN, F_CREATOR, ",
        "F_INDATE, F_UPDATE_TIME)",
        "values (#{accountUsername,jdbcType=VARCHAR}, #{accountPassword,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{isDelete,jdbcType=INTEGER}, ",
        "#{isLogin,jdbcType=INTEGER}, #{creator,jdbcType=BIGINT}, ",
        "#{indate,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="accountId", before=false, resultType=Long.class)
    int insert(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int insertSelective(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    List<AccountEntity> selectByExample(AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Select({
        "select",
        "F_ACCOUNT_ID, F_ACCOUNT_USERNAME, F_ACCOUNT_PASSWORD, F_NICKNAME, F_IS_DELETE, ",
        "F_IS_LOGIN, F_CREATOR, F_INDATE, F_UPDATE_TIME",
        "from t_account",
        "where F_ACCOUNT_ID = #{accountId,jdbcType=BIGINT}"
    })
    @ResultMap("com.ddz.domain.mapper.AccountEntityMapper.BaseResultMap")
    AccountEntity selectByPrimaryKey(Long accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccountEntity record, @Param("example") AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExample(@Param("record") AccountEntity record, @Param("example") AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByPrimaryKeySelective(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Update({
        "update t_account",
        "set F_ACCOUNT_USERNAME = #{accountUsername,jdbcType=VARCHAR},",
          "F_ACCOUNT_PASSWORD = #{accountPassword,jdbcType=VARCHAR},",
          "F_NICKNAME = #{nickname,jdbcType=VARCHAR},",
          "F_IS_DELETE = #{isDelete,jdbcType=INTEGER},",
          "F_IS_LOGIN = #{isLogin,jdbcType=INTEGER},",
          "F_CREATOR = #{creator,jdbcType=BIGINT},",
          "F_INDATE = #{indate,jdbcType=TIMESTAMP},",
          "F_UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where F_ACCOUNT_ID = #{accountId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AccountEntity record);
}