package com.ddz.domain.mapper;

import com.ddz.domain.entity.AccountRoleEntity;
import com.ddz.domain.entity.AccountRoleEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AccountRoleEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    long countByExample(AccountRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int deleteByExample(AccountRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Delete({
        "delete from t_account_role",
        "where F_ACCOUNT_ROLE_ID = #{accountRoleId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long accountRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Insert({
        "insert into t_account_role (F_ACCOUNT_ID, F_ROLE_ID)",
        "values (#{accountId,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="accountRoleId", before=false, resultType=Long.class)
    int insert(AccountRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int insertSelective(AccountRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    List<AccountRoleEntity> selectByExample(AccountRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Select({
        "select",
        "F_ACCOUNT_ROLE_ID, F_ACCOUNT_ID, F_ROLE_ID",
        "from t_account_role",
        "where F_ACCOUNT_ROLE_ID = #{accountRoleId,jdbcType=BIGINT}"
    })
    @ResultMap("com.ddz.domain.mapper.AccountRoleEntityMapper.BaseResultMap")
    AccountRoleEntity selectByPrimaryKey(Long accountRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccountRoleEntity record, @Param("example") AccountRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExample(@Param("record") AccountRoleEntity record, @Param("example") AccountRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByPrimaryKeySelective(AccountRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Update({
        "update t_account_role",
        "set F_ACCOUNT_ID = #{accountId,jdbcType=BIGINT},",
          "F_ROLE_ID = #{roleId,jdbcType=BIGINT}",
        "where F_ACCOUNT_ROLE_ID = #{accountRoleId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AccountRoleEntity record);
}