package com.ddz.domain.mapper;

import com.ddz.domain.entity.ActivityShareEntity;
import com.ddz.domain.entity.ActivityShareEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ActivityShareEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    long countByExample(ActivityShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int deleteByExample(ActivityShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Delete({
        "delete from t_activity_share",
        "where F_ACTIVITY_SHARE_ID = #{activityShareId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long activityShareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Insert({
        "insert into t_activity_share (F_ACTIVITY_ID, F_SHARED_ID, ",
        "F_USER_ID, F_INDATE)",
        "values (#{activityId,jdbcType=BIGINT}, #{sharedId,jdbcType=BIGINT}, ",
        "#{userId,jdbcType=BIGINT}, #{indate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="activityShareId", before=false, resultType=Long.class)
    int insert(ActivityShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int insertSelective(ActivityShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    List<ActivityShareEntity> selectByExample(ActivityShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Select({
        "select",
        "F_ACTIVITY_SHARE_ID, F_ACTIVITY_ID, F_SHARED_ID, F_USER_ID, F_INDATE",
        "from t_activity_share",
        "where F_ACTIVITY_SHARE_ID = #{activityShareId,jdbcType=BIGINT}"
    })
    @ResultMap("com.ddz.domain.mapper.ActivityShareEntityMapper.BaseResultMap")
    ActivityShareEntity selectByPrimaryKey(Long activityShareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") ActivityShareEntity record, @Param("example") ActivityShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByExample(@Param("record") ActivityShareEntity record, @Param("example") ActivityShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByPrimaryKeySelective(ActivityShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_share
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Update({
        "update t_activity_share",
        "set F_ACTIVITY_ID = #{activityId,jdbcType=BIGINT},",
          "F_SHARED_ID = #{sharedId,jdbcType=BIGINT},",
          "F_USER_ID = #{userId,jdbcType=BIGINT},",
          "F_INDATE = #{indate,jdbcType=TIMESTAMP}",
        "where F_ACTIVITY_SHARE_ID = #{activityShareId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ActivityShareEntity record);
}