package com.ddz.domain.mapper;

import com.ddz.domain.entity.ActivityEntity;
import com.ddz.domain.entity.ActivityEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ActivityEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    long countByExample(ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int deleteByExample(ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Delete({
        "delete from t_activity",
        "where F_ACTIVITY_ID = #{activityId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Insert({
        "insert into t_activity (F_ACTIVITY_KEY, F_ACTIVITY_NAME, ",
        "F_DESCRIBE, F_REMARK, ",
        "F_INDATE, F_IS_DELETE, ",
        "F_UPDATE_TIME)",
        "values (#{activityKey,jdbcType=VARCHAR}, #{activityName,jdbcType=VARCHAR}, ",
        "#{describe,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{indate,jdbcType=TIMESTAMP}, #{isDelete,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="activityId", before=false, resultType=Long.class)
    int insert(ActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int insertSelective(ActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    List<ActivityEntity> selectByExample(ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Select({
        "select",
        "F_ACTIVITY_ID, F_ACTIVITY_KEY, F_ACTIVITY_NAME, F_DESCRIBE, F_REMARK, F_INDATE, ",
        "F_IS_DELETE, F_UPDATE_TIME",
        "from t_activity",
        "where F_ACTIVITY_ID = #{activityId,jdbcType=BIGINT}"
    })
    @ResultMap("com.ddz.domain.mapper.ActivityEntityMapper.BaseResultMap")
    ActivityEntity selectByPrimaryKey(Long activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") ActivityEntity record, @Param("example") ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByExample(@Param("record") ActivityEntity record, @Param("example") ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByPrimaryKeySelective(ActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Update({
        "update t_activity",
        "set F_ACTIVITY_KEY = #{activityKey,jdbcType=VARCHAR},",
          "F_ACTIVITY_NAME = #{activityName,jdbcType=VARCHAR},",
          "F_DESCRIBE = #{describe,jdbcType=VARCHAR},",
          "F_REMARK = #{remark,jdbcType=VARCHAR},",
          "F_INDATE = #{indate,jdbcType=TIMESTAMP},",
          "F_IS_DELETE = #{isDelete,jdbcType=INTEGER},",
          "F_UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where F_ACTIVITY_ID = #{activityId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ActivityEntity record);
}