package com.ddz.domain.mapper;

import com.ddz.domain.entity.MenuRoleEntity;
import com.ddz.domain.entity.MenuRoleEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface MenuRoleEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    long countByExample(MenuRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int deleteByExample(MenuRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Delete({
        "delete from t_menu_role",
        "where F_MENU_ROLE_ID = #{menuRoleId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long menuRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Insert({
        "insert into t_menu_role (F_MENU_ID, F_ROLE_ID)",
        "values (#{menuId,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="menuRoleId", before=false, resultType=Long.class)
    int insert(MenuRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int insertSelective(MenuRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    List<MenuRoleEntity> selectByExample(MenuRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Select({
        "select",
        "F_MENU_ROLE_ID, F_MENU_ID, F_ROLE_ID",
        "from t_menu_role",
        "where F_MENU_ROLE_ID = #{menuRoleId,jdbcType=BIGINT}"
    })
    @ResultMap("com.ddz.domain.mapper.MenuRoleEntityMapper.BaseResultMap")
    MenuRoleEntity selectByPrimaryKey(Long menuRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") MenuRoleEntity record, @Param("example") MenuRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExample(@Param("record") MenuRoleEntity record, @Param("example") MenuRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByPrimaryKeySelective(MenuRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Update({
        "update t_menu_role",
        "set F_MENU_ID = #{menuId,jdbcType=BIGINT},",
          "F_ROLE_ID = #{roleId,jdbcType=BIGINT}",
        "where F_MENU_ROLE_ID = #{menuRoleId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MenuRoleEntity record);
}