package com.ddz.domain.mapper;

import com.ddz.domain.entity.MenuEntity;
import com.ddz.domain.entity.MenuEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface MenuEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    long countByExample(MenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int deleteByExample(MenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Delete({
        "delete from t_menu",
        "where F_MENU_ID = #{menuId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Insert({
        "insert into t_menu (F_PARENT_ID, F_MENU_NAME, ",
        "F_URL, F_PERMS, F_TYPE, ",
        "F_ICON, F_ORDER_NUM, ",
        "F_INDATE, F_UPDATE_TIME)",
        "values (#{parentId,jdbcType=INTEGER}, #{menuName,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{perms,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{icon,jdbcType=VARCHAR}, #{orderNum,jdbcType=INTEGER}, ",
        "#{indate,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="menuId", before=false, resultType=Integer.class)
    int insert(MenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int insertSelective(MenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    List<MenuEntity> selectByExample(MenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Select({
        "select",
        "F_MENU_ID, F_PARENT_ID, F_MENU_NAME, F_URL, F_PERMS, F_TYPE, F_ICON, F_ORDER_NUM, ",
        "F_INDATE, F_UPDATE_TIME",
        "from t_menu",
        "where F_MENU_ID = #{menuId,jdbcType=INTEGER}"
    })
    @ResultMap("com.ddz.domain.mapper.MenuEntityMapper.BaseResultMap")
    MenuEntity selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") MenuEntity record, @Param("example") MenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExample(@Param("record") MenuEntity record, @Param("example") MenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByPrimaryKeySelective(MenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Update({
        "update t_menu",
        "set F_PARENT_ID = #{parentId,jdbcType=INTEGER},",
          "F_MENU_NAME = #{menuName,jdbcType=VARCHAR},",
          "F_URL = #{url,jdbcType=VARCHAR},",
          "F_PERMS = #{perms,jdbcType=VARCHAR},",
          "F_TYPE = #{type,jdbcType=INTEGER},",
          "F_ICON = #{icon,jdbcType=VARCHAR},",
          "F_ORDER_NUM = #{orderNum,jdbcType=INTEGER},",
          "F_INDATE = #{indate,jdbcType=TIMESTAMP},",
          "F_UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where F_MENU_ID = #{menuId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MenuEntity record);
}