package com.ddz.domain.mapper;

import com.ddz.domain.entity.RoleEntity;
import com.ddz.domain.entity.RoleEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface RoleEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    long countByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int deleteByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Delete({
        "delete from t_role",
        "where F_ROLE_ID = #{roleId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Insert({
        "insert into t_role (F_ROLE_NAME, F_REMARK, ",
        "F_CREATOR, F_INDATE, ",
        "F_UPDATE_TIME)",
        "values (#{roleName,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{creator,jdbcType=BIGINT}, #{indate,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="roleId", before=false, resultType=Long.class)
    int insert(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int insertSelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    List<RoleEntity> selectByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Select({
        "select",
        "F_ROLE_ID, F_ROLE_NAME, F_REMARK, F_CREATOR, F_INDATE, F_UPDATE_TIME",
        "from t_role",
        "where F_ROLE_ID = #{roleId,jdbcType=BIGINT}"
    })
    @ResultMap("com.ddz.domain.mapper.RoleEntityMapper.BaseResultMap")
    RoleEntity selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByExample(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    int updateByPrimaryKeySelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon May 18 17:22:44 CST 2020
     */
    @Update({
        "update t_role",
        "set F_ROLE_NAME = #{roleName,jdbcType=VARCHAR},",
          "F_REMARK = #{remark,jdbcType=VARCHAR},",
          "F_CREATOR = #{creator,jdbcType=BIGINT},",
          "F_INDATE = #{indate,jdbcType=TIMESTAMP},",
          "F_UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where F_ROLE_ID = #{roleId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(RoleEntity record);
}