package com.ddz.domain.mapper;

import com.ddz.domain.entity.UserVoiceEntity;
import com.ddz.domain.entity.UserVoiceEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserVoiceEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    long countByExample(UserVoiceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int deleteByExample(UserVoiceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Delete({
        "delete from t_user_voice",
        "where F_USER_VOICE_ID = #{userVoiceId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long userVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Insert({
        "insert into t_user_voice (F_USER_ID, F_VOICE_PATH, ",
        "F_VOICE_MESSAGE, F_IS_DELETE, ",
        "F_INDATE, F_UPDATE_TIME)",
        "values (#{userId,jdbcType=BIGINT}, #{voicePath,jdbcType=VARCHAR}, ",
        "#{voiceMessage,jdbcType=VARCHAR}, #{isDelete,jdbcType=INTEGER}, ",
        "#{indate,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="userVoiceId", before=false, resultType=Long.class)
    int insert(UserVoiceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int insertSelective(UserVoiceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    List<UserVoiceEntity> selectByExample(UserVoiceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Select({
        "select",
        "F_USER_VOICE_ID, F_USER_ID, F_VOICE_PATH, F_VOICE_MESSAGE, F_IS_DELETE, F_INDATE, ",
        "F_UPDATE_TIME",
        "from t_user_voice",
        "where F_USER_VOICE_ID = #{userVoiceId,jdbcType=BIGINT}"
    })
    @ResultMap("com.ddz.domain.mapper.UserVoiceEntityMapper.BaseResultMap")
    UserVoiceEntity selectByPrimaryKey(Long userVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserVoiceEntity record, @Param("example") UserVoiceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByExample(@Param("record") UserVoiceEntity record, @Param("example") UserVoiceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    int updateByPrimaryKeySelective(UserVoiceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_voice
     *
     * @mbg.generated Sat Apr 04 11:02:05 CST 2020
     */
    @Update({
        "update t_user_voice",
        "set F_USER_ID = #{userId,jdbcType=BIGINT},",
          "F_VOICE_PATH = #{voicePath,jdbcType=VARCHAR},",
          "F_VOICE_MESSAGE = #{voiceMessage,jdbcType=VARCHAR},",
          "F_IS_DELETE = #{isDelete,jdbcType=INTEGER},",
          "F_INDATE = #{indate,jdbcType=TIMESTAMP},",
          "F_UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where F_USER_VOICE_ID = #{userVoiceId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserVoiceEntity record);
}