spring:
  profiles:
    include: datasource-dev
  application:
      name: voice-backstage
  #thymelea模板配置
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true

server:
  # context-path: /myboot
  session-timeout: 1800
  tomcat:
      max-threads: 1000
      min-spare-threads: 30
  port: 8771
  uri-encoding: utf-8

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${voice.eureka.instance.hostname}:${voice.eureka.instance.port}/eureka/

